name: Flutter CI/CD

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.1'

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter analyze

  deploy:
    name: Deploy Pull Request to Dev
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/pull/*/merge'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.1'

      - name: Get dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

  get_review_status:
    name: Get Pull Request Review Status
    needs: deploy
    runs-on: ubuntu-latest
    outputs:
      review_status: ${{ steps.review_job.outputs.review_status }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Pull Request Reviews
        id: review_job
        run: echo "::set-output name=review_status::$(gh pr view ${{ github.event.pull_request.number }} --json state -q '.state')"

  merge:
    name: Merge Pull Request
    needs: [deploy, get_review_status]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/pull/*/merge' && needs.get_review_status.outputs.review_status == 'APPROVED'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Merge Pull Request
        uses: pascalgn/automerge-action@v0.9.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
